package me.vorps.hub.shop;

import lombok.Getter;

/**
 * Project Hub Created by Vorps on 04/03/2016 at 21:03.
 */
public enum ShopManager {
    CHAINMAIL_BOOTS("Chainmail_boots"),
    GOLD_BOOTS("Gold_boots"),
    IRON_BOOTS("Iron_boots"),
    DIAMOND_BOOTS("Diamond_boots"),
    LEATHER_BOOTS_AQUA("Leather_boots_aqua"),
    LEATHER_BOOTS_BLACK("Leather_boots_black"),
    LEATHER_BOOTS_BLUE("Leather_boots_blue"),
    LEATHER_BOOTS_FUCHSIA("Leather_boots_fuchsia"),
    LEATHER_BOOTS_GRAY("Leather_boots_gray"),
    LEATHER_BOOTS_GREEN("Leather_boots_green"),
    LEATHER_BOOTS_LIME("Leather_boots_lime"),
    LEATHER_BOOTS_MAROON("Leather_boots_maroon"),
    LEATHER_BOOTS_NAVY("Leather_boots_navy"),
    LEATHER_BOOTS_OLIVE("Leather_boots_olive"),
    LEATHER_BOOTS_ORANGE("Leather_boots_orange"),
    LEATHER_BOOTS_PURPLE("Leather_boots_purple"),
    LEATHER_BOOTS_RED("Leather_boots_red"),
    LEATHER_BOOTS_SILVER("Leather_boots_silver"),
    LEATHER_BOOTS_TEAL("Leather_boots_teal"),
    LEATHER_BOOTS_WHITE("Leather_boots_white"),
    LEATHER_BOOTS_YELLOW("Leather_boots_yellow"),

    CHAINMAIL_CHESTPLATE("Chainmail_chestplate"),
    GOLD_CHESTPLATE("Gold_chestplate"),
    IRON_CHESTPLATE("Iron_chestplate"),
    DIAMOND_CHESTPLATE("Diamond_chestplate"),
    LEATHER_CHESTPLATE_AQUA("Leather_chestplate_aqua"),
    LEATHER_CHESTPLATE_BLACK("Leather_chestplate_black"),
    LEATHER_CHESTPLATE_BLUE("Leather_chestplate_blue"),
    LEATHER_CHESTPLATE_FUCHSIA("Leather_chestplate_fuchsia"),
    LEATHER_CHESTPLATE_GRAY("Leather_chestplate_gray"),
    LEATHER_CHESTPLATE_GREEN("Leather_chestplate_green"),
    LEATHER_CHESTPLATE_LIME("Leather_chestplate_lime"),
    LEATHER_CHESTPLATE_MAROON("Leather_chestplate_maroon"),
    LEATHER_CHESTPLATE_NAVY("Leather_chestplate_navy"),
    LEATHER_CHESTPLATE_OLIVE("Leather_chestplate_olive"),
    LEATHER_CHESTPLATE_ORANGE("Leather_chestplate_orange"),
    LEATHER_CHESTPLATE_PURPLE("Leather_chestplate_purple"),
    LEATHER_CHESTPLATE_RED("Leather_chestplate_red"),
    LEATHER_CHESTPLATE_SILVER("Leather_chestplate_silver"),
    LEATHER_CHESTPLATE_TEAL("Leather_chestplate_teal"),
    LEATHER_CHESTPLATE_WHITE("Leather_chestplate_white"),
    LEATHER_CHESTPLATE_YELLOW("Leather_chestplate_yellow"),


    CHAINMAIL_LEGGINGS("Chainmail_leggings"),
    GOLD_LEGGINGS("Gold_leggings"),
    IRON_LEGGINGS("Iron_leggings"),
    DIAMOND_LEGGINGS("Diamond_leggings"),
    LEATHER_LEGGINGS_AQUA("Leather_leggings_aqua"),
    LEATHER_LEGGINGS_BLACK("Leather_leggings_black"),
    LEATHER_LEGGINGS_BLUE("Leather_leggings_blue"),
    LEATHER_LEGGINGS_FUCHSIA("Leather_leggings_fuchsia"),
    LEATHER_LEGGINGS_GRAY("Leather_leggings_gray"),
    LEATHER_LEGGINGS_GREEN("Leather_leggings_green"),
    LEATHER_LEGGINGS_LIME("Leather_leggings_lime"),
    LEATHER_LEGGINGS_MAROON("Leather_leggings_maroon"),
    LEATHER_LEGGINGS_NAVY("Leather_leggings_navy"),
    LEATHER_LEGGINGS_OLIVE("Leather_leggings_olive"),
    LEATHER_LEGGINGS_ORANGE("Leather_leggings_orange"),
    LEATHER_LEGGINGS_PURPLE("Leather_leggings_purple"),
    LEATHER_LEGGINGS_RED("Leather_leggings_red"),
    LEATHER_LEGGINGS_SILVER("Leather_leggings_silver"),
    LEATHER_LEGGINGS_TEAL("Leather_leggings_teal"),
    LEATHER_LEGGINGS_WHITE("Leather_leggings_white"),
    LEATHER_LEGGINGS_YELLOW("Leather_leggings_yellow"),

    CHAINMAIL_HELMET("Chainmail_helmet"),
    GOLD_HELMET("Gold_helmet"),
    IRON_HELMET("Iron_helmet"),
    DIAMOND_HELMET("Diamond_helmet"),
    LEATHER_HELMET_AQUA("Leather_helmet_aqua"),
    LEATHER_HELMET_BLACK("Leather_helmet_black"),
    LEATHER_HELMET_BLUE("Leather_helmet_blue"),
    LEATHER_HELMET_FUCHSIA("Leather_helmet_fuchsia"),
    LEATHER_HELMET_GRAY("Leather_helmet_gray"),
    LEATHER_HELMET_GREEN("Leather_helmet_green"),
    LEATHER_HELMET_LIME("Leather_helmet_lime"),
    LEATHER_HELMET_MAROON("Leather_helmet_maroon"),
    LEATHER_HELMET_NAVY("Leather_helmet_navy"),
    LEATHER_HELMET_OLIVE("Leather_helmet_olive"),
    LEATHER_HELMET_ORANGE("Leather_helmet_orange"),
    LEATHER_HELMET_PURPLE("Leather_helmet_purple"),
    LEATHER_HELMET_RED("Leather_helmet_red"),
    LEATHER_HELMET_SILVER("Leather_helmet_silver"),
    LEATHER_HELMET_TEAL("Leather_helmet_teal"),
    LEATHER_HELMET_WHITE("Leather_helmet_white"),
    LEATHER_HELMET_YELLOW("Leather_helmet_yellow"),

    HELMET_PIG("Helmet_pig"),
    HELMET_COW("Helmet_cow"),
    HELMET_SHEEP("Helmet_sheep"),
    HELMET_RABBIT("Helmet_rabbit"),
    HELMET_SILVERFISH("Helmet_silverfish"),
    HELMET_ZOMBIE("Helmet_zombie"),
    HELMET_SPIDER("Helmet_spider"),
    HELMET_CREEPER("Helmet_creeper"),
    HELMET_SKELETON("Helmet_skeleton"),
    HELMET_PIG_ZOMBIE("Helmet_pig_zombie"),
    HELMET_CAVE_SPIDER("Helmet_cave_spider"),
    HELMET_OCELOT("Helmet_ocelot"),
    HELMET_WOLF("Helmet_wolf"),
    HELMET_CAT("Helmet_cat"),
    HELMET_CHICKEN("Helmet_chicken"),
    HELMET_VILLAGER("Helmet_villager"),
    HELMET_WSKELETON("Helmet_wskeleton"),
    HELMET_SLIME("Helmet_slime"),
    HELMET_LAVA_SLIME("Helmet_lava_slime"),
    HELMET_ENDERMAN("Helmet_enderman"),
    HELMET_ENDERMITE("Helmet_endermite"),
    HELMET_MUSHROOM_COW("Helmet_mushroom_cow"),
    HELMET_GOLEM("Helmet_golem"),
    HELMET_SNOW_GOLEM("Helmet_snow_golem"),
    HELMET_WITCH("Helmet_witch"),
    HELMET_SQUID("Helmet_squid"),
    HELMET_BLAZE("Helmet_blaze"),
    HELMET_GUARDIAN("Helmet_guardian"),
    HELMET_GHAST("Helmet_ghast"),
    HELMET_WITHER("Helmet_wither"),
    HELMET_ENDERDRAGON("Helmet_enderdragon"),

    HELMET_CHEST("Helmet_chest"),
    HELMET_ENCHANTMENT_TABLE("Helmet_enchantment_table"),
    HELMET_ANVIL("Helmet_anvil"),
    HELMET_ENDER_CHEST("Helmet_ender_chest"),
    HELMET_FURNACE("Helmet_furnace"),
    HELMET_DROPPER("Helmet_dropper"),
    HELMET_DISPENSER("Helmet_dispenser"),
    HELMET_NOTE_BLOCK("Helmet_note_block"),
    HELMET_TNT("Helmet_tnt"),
    HELMET_PISTON_BASE("Helmet_piston"),
    HELMET_SLIME_BLOCK("Helmet_slime_block"),
    HELMET_MELON_BLOCK("Helmet_melon_block"),
    HELMET_HAY_BLOCK("Helmet_hay_block"),
    HELMET_CRAFT_TABLE("Helmet_craft_table"),
    HELMET_BOOKSHELF("Helmet_bookshelf"),
    HELMET_GLASS("Helmet_pumpkin"),
    HELMET_PUMPKIN("Helmet_jack_o_lantern"),
    HELMET_JACK_O_LANTERN("Helmet_red_mushroom"),
    HELMET_RED_MUSHROOM("Helmet_red_mushroom"),
    HELMET_IRON_BLOCK("Helmet_iron_block"),
    HELMET_LAPIS_BLOCK("Helmet_lapis_block"),
    HELMET_REDSTONE_BLOCK("Helmet_redstone_block"),
    HELMET_GOLD_BLOCK("Helmet_gold_block"),
    HELMET_EMERALD_BLOCK("Helmet_emerald_block"),
    HELMET_DIAMOND_BLOCK("Helmet_diamond_block"),
    HELMET_BEACON("Helmet_beacon"),

    PARTICULE_BULLE("Particule_Bulles"),
    PARTICULE_COLERE("Particule_Colere"),
    PARTICULE_COEUR("Particule_Coeurs"),
    PARTICULE_VERTE("Particule_Vertes"),
    PARTICULE_FUMEE("Particule_Fumee"),
    PARTICULE_POTION("Particule_Potion"),
    PARTICULE_DEGAT_MAGIQUE("Particule_Degats_Magiques"),
    PARTICULE_SPASH_POTION("Particule_Splash_Potion"),
    PARTICULE_SORCIERE("Particule_Sorciere"),
    PARTICULE_NOTE_MUSIQUE("Particule_Note_Musique"),
    PARTICULE_NUAGE_BLANC("Particule_Nuage_Blanc"),
    PARTICULE_LAVE("Particule_Lave"),
    PARTICULE_SLIME("Particule_Slime"),
    PARTICULE_FLAME("Particule_Flame"),
    PARTICULE_DEGATS("Particule_Degats"),
    PARTICULE_ENCHANTEMENT("Particule_Enchantement"),

    PETS_PIG("Pets_Pig"),
    PETS_COW("Pets_Cow"),
    PETS_SHEEP("Pets_Sheep"),
    PETS_RABBIT("Pets_Rabbit"),
    PETS_HORSE("Pets_Horse"),
    PETS_SILVERFISH("Pets_Silverfish"),
    PETS_ZOMBIE("Pets_Zombie"),
    PETS_SPIDER("Pets_Spider"),
    PETS_CREEPER("Pets_Creeper"),
    PETS_SKELETON("Pets_Skeleton"),
    PETS_PIGZOMBIE("Pets_Pig_Zombie"),
    PETS_CAVESPIDER("Pets_Cave_Spider"),
    PETS_OCELOT("Pets_Ocelot"),
    PETS_WOLF("Pets_Wolf"),
    PETS_CAT("Pets_Cat"),
    PETS_CHICKEN("Pets_Chicken"),
    PETS_VILLAGER("Pets_Villager"),
    PETS_WSKELETON("Pets_Wither_Skeleton"),
    PETS_SLIME("Pets_Slime"),
    PETS_LAVASLIME("Pets_Lava_Slime"),
    PETS_ENDERMAN("Pets_Enderman"),
    PETS_ENDERMITE("Pets_Endermite"),
    PETS_MUSHROOMCOW("Pets_Mushroom_Cow"),
    PETS_GOLEM("Pets_Golem"),
    PETS_SNOWGOLEM("Pets_Snow_Golem"),
    PETS_WITCH("Pets_Witch"),
    PETS_SQUID("Pets_Squid"),
    PETS_SPAWN_CREEPER("Pets_Spawn_Creeper"),
    PETS_BLAZE("Pets_Blaze"),
    PETS_GUARDIAN("Pets_Guardian"),
    PETS_GHAST("Pets_Ghast"),
    PETS_ZOMBIE_GIANT("Pets_Zombie_Giant"),
    PETS_WITHER("Pets_Wither"),
    PETS_ENDERDRAGON("Pets_Enderdragon"),

    GADGETS_BAT("Gadgets_bat"),
    GADGETS_COLOR("Gadgets_Color"),
    VIP("VIP"),
    HEROS("Héros"),
    LEGENDE("Légende"),
    BONUS_25("Bonus 25%"),
    BONUS_50("Bonus 50%"),
    BONUS_75("Bonus 75%");
    private @Getter String nameProduct;

    ShopManager(String nameProduct){
        this.nameProduct = nameProduct;
    }
}
