package sirmc.vorps.menu;

import org.bukkit.Bukkit;
import org.bukkit.Color;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.Inventory;

import sirmc.vorps.PlayerHub;
import sirmc.vorps.utils.Item;
import sirmc.vorps.utils.Purchase;

public class MenuHelmet {

	public static void HubmenuHelmetPage1(PlayerHub playerHub){
		Purchase purchase = new Purchase(playerHub, "ce chapeau sur votre tête.");
		Inventory menuHelmetPage1 = Bukkit.createInventory(null, 54, "§6Boutique > Costumes > Chapeaux");
		menuHelmetPage1.setItem(0, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(1, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage1.setItem(2, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage1.setItem(3, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(4, new Item(Material.GOLD_HELMET).withName("§6Chapeaux").withEnchant(Enchantment.ARROW_DAMAGE, 1).hideEnchant(true).get());
		menuHelmetPage1.setItem(5, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage1.setItem(6, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(7, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage1.setItem(8, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage1.setItem(9, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage1.setItem(10, new Item(Material.CHAINMAIL_HELMET).withName("§6Cotte de maille").withLore(purchase.purchase("Chainmail_helmet")).get());
		menuHelmetPage1.setItem(11, new Item(Material.GOLD_HELMET).withName("§6Or").withLore(purchase.purchase("Gold_helmet")).get());
		menuHelmetPage1.setItem(13, new Item(Material.BARRIER).withName("§6Retirer mon chapeaux").withLore(new String[] {"§7Retire votre chapeaux actuel"}).get());
		menuHelmetPage1.setItem(15, new Item(Material.IRON_HELMET).withName("§6Fer").withLore(purchase.purchase("Iron_helmet")).get());
		menuHelmetPage1.setItem(16, new Item(Material.DIAMOND_HELMET).withName("§6Diamant").withLore(purchase.purchase("Diamond_helmet")).get());
		menuHelmetPage1.setItem(17, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(18, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage1.setItem(21, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.AQUA).withLore(purchase.purchase("Leather_helmet_aqua")).get());
		menuHelmetPage1.setItem(22, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.BLACK).withLore(purchase.purchase("Leather_helmet_black")).get());
		menuHelmetPage1.setItem(23, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.BLUE).withLore(purchase.purchase("Leather_helmet_blue")).get());
		menuHelmetPage1.setItem(26, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage1.setItem(27, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(28, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.FUCHSIA).withLore(purchase.purchase("Leather_helmet_fuchsia")).get());
		menuHelmetPage1.setItem(29, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.GRAY).withLore(purchase.purchase("Leather_helmet_gray")).get());
		menuHelmetPage1.setItem(30, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.GREEN).withLore(purchase.purchase("Leather_helmet_green")).get());
		menuHelmetPage1.setItem(31, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.LIME).withLore(purchase.purchase("Leather_helmet_lime")).get());
		menuHelmetPage1.setItem(32, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.MAROON).withLore(purchase.purchase("Leather_helmet_maroon")).get());
		menuHelmetPage1.setItem(33, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.NAVY).withLore(purchase.purchase("Leather_helmet_navy")).get());
		menuHelmetPage1.setItem(34, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.OLIVE).withLore(purchase.purchase("Leather_helmet_olive")).get());
		menuHelmetPage1.setItem(35, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(36, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(37, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.ORANGE).withLore(purchase.purchase("Leather_helmet_orange")).get());
		menuHelmetPage1.setItem(38, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.PURPLE).withLore(purchase.purchase("Leather_helmet_purple")).get());
		menuHelmetPage1.setItem(39, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.RED).withLore(purchase.purchase("Leather_helmet_red")).get());
		menuHelmetPage1.setItem(40, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.SILVER).withLore(purchase.purchase("Leather_helmet_silver")).get());
		menuHelmetPage1.setItem(41, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.TEAL).withLore(purchase.purchase("Leather_helmet_teal")).get());
		menuHelmetPage1.setItem(42, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.WHITE).withLore(purchase.purchase("Leather_helmet_white")).get());
		menuHelmetPage1.setItem(43, new Item(Material.LEATHER_HELMET).withName("§6Cuir coloré").withColor(Color.YELLOW).withLore(purchase.purchase("Leather_helmet_yellow")).get());
		menuHelmetPage1.setItem(44, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(45, new Item(Material.ARROW).withName("§6<-Retour").withLore(new String[] {"§7Retour au menu Costumes"}).get());
		menuHelmetPage1.setItem(46, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(47, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage1.setItem(48, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage1.setItem(49, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(50, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage1.setItem(51, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage1.setItem(52, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage1.setItem(53, new Item(Material.PAPER).withName("§6Page Suivante -> Têtes").withLore(new String[] {"§7Page Têtes"}).get());
		Bukkit.getPlayer(playerHub.getPlayerName()).openInventory(menuHelmetPage1);
	}
	
	public static void HubMenuHelmetPage2(PlayerHub playerHub){
		Purchase purchase = new Purchase(playerHub, "ce chapeau sur votre tête.");
		Inventory menuHelmetPage2 = Bukkit.createInventory(null, 54, "§6Boutique > Costumes > Têtes");
		menuHelmetPage2.setItem(0, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage2.setItem(1, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage2.setItem(2, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage2.setItem(3, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage2.setItem(4, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage2.setItem(5, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage2.setItem(6, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage2.setItem(7, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage2.setItem(8, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage2.setItem(10, new Item("MHF_Pig").withName("§6Cochon").withLore(purchase.purchase("Helmet_pig")).get());
		menuHelmetPage2.setItem(11, new Item("MHF_Cow").withName("§6Vache").withLore(purchase.purchase("Helmet_cow")).get());
		menuHelmetPage2.setItem(13, new Item(Material.BARRIER).withName("§6Retirer mon chapeaux").withLore(new String[] {"§7Retire votre chapeaux actuel"}).get());
		menuHelmetPage2.setItem(15, new Item("MHF_Sheep").withName("§6Mouton").withLore(purchase.purchase("Helmet_sheep")).get());
		menuHelmetPage2.setItem(16, new Item("MHF_Rabbit").withName("§6Lapin").withLore(purchase.purchase("Helmet_rabbit")).get());
		menuHelmetPage2.setItem(18, new Item("MHF_SilverFish").withName("§6SilverFish").withLore(purchase.purchase("Helmet_silverFish")).get());
		menuHelmetPage2.setItem(19, new Item("MHF_Zombie").withName("§6Zombie").withLore(purchase.purchase("Helmet_zombie")).get());
		menuHelmetPage2.setItem(20, new Item("MHF_Spider").withName("§6Araignée").withLore(purchase.purchase("Helmet_spider")).get());
		menuHelmetPage2.setItem(21, new Item("MHF_Creeper").withName("§6Creeper").withLore(purchase.purchase("Helmet_creeper")).get());
		menuHelmetPage2.setItem(22, new Item("MHF_Skeleton").withName("§6Squelette").withLore(purchase.purchase("Helmet_skeleton")).get());
		menuHelmetPage2.setItem(23, new Item("MHF_PigZombie").withName("§6Cochon Zombie").withLore(purchase.purchase("Helmet_pigZombie")).get());
		menuHelmetPage2.setItem(24, new Item("MHF_CaveSpider").withName("§6Araignée des caves").withLore(purchase.purchase("Helmet_caveSpider")).get());
		menuHelmetPage2.setItem(25, new Item("MHF_Ocelot").withName("§6Ocelot").withLore(purchase.purchase("Helmet_ocelot")).get());
		menuHelmetPage2.setItem(26, new Item("MHF_Wolf").withName("§6Chien").withLore(purchase.purchase("Helmet_wolf")).get());
		menuHelmetPage2.setItem(27, new Item("MHF_Cat").withName("§6Chat").withLore(purchase.purchase("Helmet_cat")).get());
		menuHelmetPage2.setItem(28, new Item("MHF_Chicken").withName("§6Poule").withLore(purchase.purchase("Helmet_chicken")).get());
		menuHelmetPage2.setItem(29, new Item("MHF_Villager").withName("§6Villageois").withLore(purchase.purchase("Helmet_villager")).get());
		menuHelmetPage2.setItem(30, new Item("MHF_WSkeleton").withName("§6Whither Skeleton").withLore(purchase.purchase("Helmet_wSkeleton")).get());
		menuHelmetPage2.setItem(31, new Item("MHF_Slime").withName("§6Slime").withLore(purchase.purchase("Helmet_slime")).get());
		menuHelmetPage2.setItem(32, new Item("MHF_LavaSlime").withName("§6Slime en Lave").withLore(purchase.purchase("Helmet_lavaSlime")).get());
		menuHelmetPage2.setItem(33, new Item("MHF_Enderman").withName("§6Enderman").withLore(purchase.purchase("Helmet_enderman")).get());
		menuHelmetPage2.setItem(34, new Item("MHF_Endermite").withName("§6EnderMite").withLore(purchase.purchase("Helmet_endermite")).get());
		menuHelmetPage2.setItem(35, new Item("MHF_MushtroomCow").withName("§6Vache Champignon").withLore(purchase.purchase("Helmet_mushtroomCow")).get());
		menuHelmetPage2.setItem(36, new Item("MHF_Golem").withName("§6Golem").withLore(purchase.purchase("Helmet_golem")).get());
		menuHelmetPage2.setItem(37, new Item("MHF_SnowGolem").withName("§6Golem des neiges").withLore(purchase.purchase("Helmet_snowGolem")).get());
		menuHelmetPage2.setItem(38, new Item("MHF_Witch").withName("§6Sorcière").withLore(purchase.purchase("Helmet_witch")).get());
		menuHelmetPage2.setItem(39, new Item("MHF_Squid").withName("§6Squid").withLore(purchase.purchase("Helmet_squid")).get());
		menuHelmetPage2.setItem(40, new Item("MHF_Blaze").withName("§6Blaze").withLore(purchase.purchase("Helmet_blaze")).get());
		menuHelmetPage2.setItem(41, new Item("MHF_Guardian").withName("§6Guardian").withLore(purchase.purchase("Helmet_guardian")).get());
		menuHelmetPage2.setItem(42, new Item("MHF_Ghast").withName("§6Ghast").withLore(purchase.purchase("Helmet_ghast")).get());
		menuHelmetPage2.setItem(43, new Item("MHF_Wither").withName("§6Wither").withLore(purchase.purchase("Helmet_wither")).get());
		menuHelmetPage2.setItem(44, new Item("MHF_EnderDragon").withName("§6Ender Dragon").withLore(purchase.purchase("Helmet_enderDragon")).get());
		menuHelmetPage2.setItem(45, new Item(Material.ARROW).withName("§6<-Retour").withLore(new String[] {"§7Retour au menu Costumes"}).get());
		menuHelmetPage2.setItem(46, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage2.setItem(47, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage2.setItem(48, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage2.setItem(49, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage2.setItem(50, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage2.setItem(51, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage2.setItem(52, new Item(Material.EMPTY_MAP).withName("§6<- Page Précedente -> Chapeaux").withLore(new String[] {"§7Retour au menu Chapeaux"}).get());
		menuHelmetPage2.setItem(53, new Item(Material.PAPER).withName("§6Page Suivante -> Block").withLore(new String[] {"§7Page Block"}).get());
		Bukkit.getPlayer(playerHub.getPlayerName()).openInventory(menuHelmetPage2);
	}
	
	public static void HubMenuHelmetPage3(PlayerHub playerHub){
		Purchase purchase = new Purchase(playerHub, "ce chapeau sur votre tête.");
		Inventory menuHelmetPage3 = Bukkit.createInventory(null, 54, "§6Boutique > Costumes > Blocks");
		menuHelmetPage3.setItem(0, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(1, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(2, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(3, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(4, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(5, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(6, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(7, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(8, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(9, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(10, new Item(Material.CHEST).withName("§6Coffre").withLore(purchase.purchase("Helmet_chest")).get());
		menuHelmetPage3.setItem(11, new Item(Material.ENCHANTMENT_TABLE).withName("§6Table d'enchante").withLore(purchase.purchase("Helmet_enchantment_table")).get());
		menuHelmetPage3.setItem(12, new Item(Material.ANVIL).withName("§6Enclume").withLore(purchase.purchase("Helmet_anvil")).get());
		menuHelmetPage3.setItem(13, new Item(Material.ENDER_CHEST).withName("§6Coffre de l'end").withLore(purchase.purchase("Helmet_ender_chest")).get());
		menuHelmetPage3.setItem(14, new Item(Material.FURNACE).withName("§6Four").withLore(purchase.purchase("Helmet_furnace")).get());
		menuHelmetPage3.setItem(15, new Item(Material.DROPPER).withName("§6Dropper").withLore(purchase.purchase("Helmet_dropper")).get());
		menuHelmetPage3.setItem(16, new Item(Material.DISPENSER).withName("§6Dispenser").withLore(purchase.purchase("Helmet_dispenser")).get());
		menuHelmetPage3.setItem(17, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(18, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(19, new Item(Material.NOTE_BLOCK).withName("§6Note Book").withLore(purchase.purchase("Helmet_note_block")).get());
		menuHelmetPage3.setItem(20, new Item(Material.TNT).withName("§6TNT").withLore(purchase.purchase("Helmet_tnt")).get());
		menuHelmetPage3.setItem(21, new Item(Material.PISTON_BASE).withName("§6Piston").withLore(purchase.purchase("Helmet_piston")).get());
		menuHelmetPage3.setItem(22, new Item(Material.SLIME_BLOCK).withName("§6Block de slime").withLore(purchase.purchase("Helmet_slime_block")).get());
		menuHelmetPage3.setItem(23, new Item(Material.MELON_BLOCK).withName("§6Pasteque").withLore(purchase.purchase("Helmet_melon_block")).get());
		menuHelmetPage3.setItem(24, new Item(Material.HAY_BLOCK).withName("§6Paille").withLore(purchase.purchase("Helmet_hay_block")).get());
		menuHelmetPage3.setItem(25, new Item(58).withData((byte) 0).withName("§6Table de craft").withLore(purchase.purchase("Helmet_craft_table")).get());
		menuHelmetPage3.setItem(26, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(27, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(29, new Item(Material.BOOKSHELF).withName("§6Bibliothèque").withLore(purchase.purchase("Helmet_bookshelf")).get());
		menuHelmetPage3.setItem(30, new Item(Material.GLASS).withName("§6Verre").withLore(purchase.purchase("Helmet_glass")).get());
		menuHelmetPage3.setItem(31, new Item(Material.PUMPKIN).withName("§6Citrouille").withLore(purchase.purchase("Helmet_pumpkin")).get());
		menuHelmetPage3.setItem(32, new Item(Material.JACK_O_LANTERN).withName("§6JACK_O_LANTERN").withLore(purchase.purchase("Helmet_jack_o_lantern")).get());
		menuHelmetPage3.setItem(33, new Item(100).withData((byte) 0).withName("§6Block champignon").withLore(purchase.purchase("Helmet_red_mushroom")).get());
		menuHelmetPage3.setItem(35, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(36, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(37, new Item(Material.IRON_BLOCK).withName("§6Block de fer").withLore(purchase.purchase("Helmet_iron_block")).get());
		menuHelmetPage3.setItem(38, new Item(Material.LAPIS_BLOCK).withName("§6Lapis").withLore(purchase.purchase("Helmet_lapis_block")).get());
		menuHelmetPage3.setItem(39, new Item(Material.REDSTONE_BLOCK).withName("§6Block de redstone").withLore(purchase.purchase("Helmet_redstone_block")).get());
		menuHelmetPage3.setItem(40, new Item(Material.GOLD_BLOCK).withName("§6Block d'or").withLore(purchase.purchase("Helmet_gold_block")).get());
		menuHelmetPage3.setItem(41, new Item(Material.EMERALD_BLOCK).withName("§6Block d'émeraude").withLore(purchase.purchase("Helmet_emerald_block")).get());
		menuHelmetPage3.setItem(42, new Item(Material.DIAMOND_BLOCK).withName("§6Block de diamand").withLore(purchase.purchase("Helmet_diamond_block")).get());
		menuHelmetPage3.setItem(43, new Item(Material.BEACON).withName("§6Beacon").withLore(purchase.purchase("Helmet_beacon")).get());
		menuHelmetPage3.setItem(44, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(45, new Item(Material.ARROW).withName("§6<-Retour").withLore(new String[] {"§7Retour au menu Costumes"}).get());
		menuHelmetPage3.setItem(46, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(47, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(48, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(49, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(50, new Item(160).withData((byte) 6).withName(" ").get());
		menuHelmetPage3.setItem(51, new Item(160).withData((byte) 2).withName(" ").get());
		menuHelmetPage3.setItem(52, new Item(160).withData((byte) 10).withName(" ").get());
		menuHelmetPage3.setItem(53, new Item(Material.EMPTY_MAP).withName("§6Page Précedente -> Têtes").withLore(new String[] {"§7Retour au menu Têtes"}).get());
		Bukkit.getPlayer(playerHub.getPlayerName()).openInventory(menuHelmetPage3);
	}
}
